# Generated by Django 3.2.2 on 2021-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_bikecompanymodel_bikemodel_servicerequestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=255)),
                ('serviceContent', models.TextField()),
                ('servicePhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
